global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["api:8000"]
  - job_name: "identity"
    static_configs:
      - targets: ["identity:8000"]
  - job_name: "inventory"
    static_configs:
      - targets: ["inventory:8000"]
  - job_name: "booking"
    static_configs:
      - targets: ["booking:8000"]
